# Generated by Django 3.0.4 on 2020-03-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoicQuotesRESTAPI', '0001_initial'),
    ]

    operations = [
    ]
